insert into Airline (id, name) values (1, 'Ryanair');
insert into Airline (id, name) values (2, 'Vueling');
insert into Airline (id, name) values (3, 'KLM');
insert into Airline (id, name) values (4, 'Iberia');
insert into Airline (id, name) values (5, 'Qatar Airways');
insert into Airline (id, name) values (6, 'Air Canada');
insert into Airline (id, name) values (7, 'Emirates');
insert into Airline (id, name) values (8, 'TAP Portugal');
insert into Airline (id, name) values (9, 'AirEuropa');
insert into Airline (id, name) values (10, 'EasyJet');

insert into Airport (id, code, name) values (1, 'ALC', 'El Altet Airport');
insert into Airport (id, code, name) values (2, 'BCN', 'El Prat Airport');
insert into Airport (id, code, name) values (3, 'MAD', 'Barajar Airport');
insert into Airport (id, code, name) values (4, 'IBZ', 'Ibiza Airport');
insert into Airport (id, code, name) values (5, 'AGP', 'Malaga Airport');
insert into Airport (id, code, name) values (6, 'LHR', 'Heathrow Airport');
insert into Airport (id, code, name) values (7, 'CDG', 'Charles de Gaulle Airport');
insert into Airport (id, code, name) values (8, 'AMS', 'Amsterdam Airport');
insert into Airport (id, code, name) values (9, 'FRA', 'Frankfurt Airport');
insert into Airport (id, code, name) values (10, 'SIN', 'Singapore Changi Airport');
insert into Airport (id, code, name) values (11, 'SFO', 'San Francisco International Airport');
insert into Airport (id, code, name) values (12, 'YYZ', 'Toronto Pearson Airport');
insert into Airport (id, code, name) values (13, 'MEX', 'Benito Suarez International Airport');
insert into Airport (id, code, name) values (14, 'LGW', 'London Gatwick Airport');
insert into Airport (id, code, name) values (15, 'HND', 'Tokyo Haneda Airport');
insert into Airport (id, code, name) values (16, 'DXB', 'Dubai International Airport');
insert into Airport (id, code, name) values (17, 'BRU', 'Brussels Airport');
insert into Airport (id, code, name) values (18, 'SOF', 'Sofia Airport');
insert into Airport (id, code, name) values (19, 'ORY', 'Paris Orly Airport');
insert into Airport (id, code, name) values (20, 'BER', 'Berlin Brandenburg Airport');
insert into Airport (id, code, name) values (21, 'MUC', 'Munich Airport');
insert into Airport (id, code, name) values (22, 'BUD', 'Budapest Airport');
insert into Airport (id, code, name) values (23, 'DUB', 'Dublin Airport');
insert into Airport (id, code, name) values (24, 'NAP', 'Naples Airport');
insert into Airport (id, code, name) values (25, 'VCE', 'Venice Airport');
insert into Airport (id, code, name) values (26, 'MLA', 'Malta Airport');
insert into Airport (id, code, name) values (27, 'LIS', 'Lisbos Airport');
insert into Airport (id, code, name) values (28, 'OPO', 'Porto Airport');
insert into Airport (id, code, name) values (29, 'ZRH', 'Zurich Airport');
insert into Airport (id, code, name) values (30, 'IST', 'Istanbul Airport');
